version: '3'

services:
  web:
  build: .
  command: python manage.py makemigrations && python manage.py migrate && python manage.py runserver 127.0.0.1:8000
  container_name: my_app
  volumes:
    -.:/my_app
  ports: 
   - "8000:8000"
